### ISSUE TITLE
Game Over theme is glitched

### ISSUE THREAD

**Issue by duckfist** [duckfist/MM2Random#142]
Likely as a result of shifting several songs around. Check the vibrato.

**Comment by NARFNra** [comment]
It seems that the vibrato pointer for this song is simply not being changed when the track is moved.

Original Pointers for track: 
from 33367: 0F
Pulse 1: 62 B3
Pulse 2: 80 B3 
Tri: 9E B3
Noise: C3 B3 
Vibrato: **D1 B3** 

Example produced file - default settings 0.4.1.34510 - seed FYPURZR
from 3377B: 0F
Pulse 1: 76 B7
Pulse 2:  94 B7
Tri: B2 B7
Noise: D7 B7
Vibrato: **D1 B3**!!

Applying the .ips music patch from the resources folder to a blank rom reveals this error at 33784.

**Comment by duckfist** [comment]
Thanks, but I already knew about this and knew what to do. Feel free to prioritize bugs labeled "Help Wanted".

**Comment by duckfist** [comment]
Sorry about the asshole comment last time, your post helped me catch up and fix this quickly after a long hiatus. Thank you, it should be fixed in the next release now.
