### ISSUE TITLE
Music List

### ISSUE THREAD

**Issue by MarioXMan** [duckfist/MM2Random#153]
I think it would be helpful to have a list of the music in the game if possible.

**Comment by MarioXMan** [comment]
Sorry, wrong location, looking for delete button

**Comment by NARFNra** [comment]
MM2Random/MM2RandoLib/Resources/music.txt contains all data for individual music tracks
 with hack or game of origin included.

**Comment by duckfist** [comment]
Sorry it took me a while to get to this.

I've thought about maybe switching the first part of the credits, where it lists some developer names along with each of the 8 robot masters, to instead show each chosen music track and the corresponding hack author.

It's not that easy to write stuff in the credits, but perhaps I just don't understand it well. The character limits are strange, and generally pretty short to write anything of use. But I'll keep this open and think about it some more, or in case someone else can contribute.

**Comment by NARFNra** [comment]
Maybe just have the program produce a .txt log file listing the song replacements?

**Comment by duckfist** [comment]
There already is a log file. Changed my mind, closing this.
