### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by GamingRetroJose** [duckfist/MM2Random#164]
Hi Duckfist. I can´t start last version, there´s no .exe file. 
Ips files doest randomize it, only characters. Help me please! Thanks in advance

**Comment by duckfist** [comment]
You may have accidentally downloaded the source code. You should download it from the "Releases" page - to be honest, it looks like GitHub recently moved this, so it's harder to see how to get there from a project's main page. Here's a direct link to the download for the latest version:
https://github.com/duckfist/MM2Random/releases/download/v0.5.0-beta/mm2rng_0.5.0.zip

Let me know if you have any other issues.
