### ISSUE TITLE
Air Fiends make Hard Man's stage impossible

### ISSUE THREAD

**Issue by Superjustinbros** [duckfist/MM2Random#87]
![mm2-rng-eoecbmo 019](https://cloud.githubusercontent.com/assets/4167951/19522872/ad0508d6-95e6-11e6-8e4f-4027c800bd06.png)
In this scenario, I cannot make the jump to the other side without an Item.
Seed is EOECBMO

**Comment by duckfist** [comment]
You can jump and pause buffer on the descent to reach the other side.  In this randomizer, anything goes, including this advanced technique.  But it should never require zip glitches to proceed.
